### ISSUE TITLE
DIA: Piney Point Algal bloom detection using DESIS

### ISSUE THREAD

**Issue by bwbaker1** [NASA-IMPACT/dia-piney-point#1]
### **Description**
The research will focus on studying algal blooms/chlorophyll a detection following a wastewater leak into Tampa Bay from the old Piney Point phosphate plant using DESIS hyperspectral imagery. 

Note: most of this analysis is replicated from the forest disturbance research (data wasn't sufficient enough).

[Notes and Links](https://docs.google.com/document/d/1g2vJN1BMuXXlHLozG9KxOFyz3VqHJzIpP7IJ99Q1KZA/edit#heading=h.5xp0tsyritd1)

### **Tasks:**
- [x] Download ground sample data 
- [x] Use quality image to extract out water and bad quality pixels (2020-2022)
- [x] Composite images by month/year - narrow down AOI based on overlap
- [x] Perform correlation analysis on spectral range (e.g., green, red, NIR, etc.)
- [x] Calculate indices based on correlation results (NDVI, NDWI, NDCI, CI-Green, CI-Red, NDRE3)
- [ ] ~Validate with ground truth data~

### **Acceptance criteria**
- [x] Initial analysis completed (cloud free imagery (before, during, and after event), mosaic, indices, time series, area calculations)
       - Once completed, we will decide if there is anything worthy of a DIA. 

### **Demo**
Initial results can be demonstrated

**Comment by bwbaker1** [comment]
@kaulfusa added this to track piney point dia (potential story depending on results).
